-- Out of memory on QD
select py_memory_allocate_oom(1);
 py_memory_allocate_oom 
------------------------
 
(1 row)

select py_memory_allocate_oom(512);
ERROR:  plcontainer: Error receiving data from the client. Maybe retry later. (plcontainer.c:255)
select py_memory_allocate_oom(1);
 py_memory_allocate_oom 
------------------------
 
(1 row)

select py_memory_allocate_normal(512);
 py_memory_allocate_normal 
---------------------------
 
(1 row)

select py_memory_allocate_oom(512);
ERROR:  plcontainer: Error receiving data from the client. Maybe retry later. (plcontainer.c:255)
select py_memory_allocate_normal(512);
 py_memory_allocate_normal 
---------------------------
 
(1 row)

-- Out of memory on QE
select count(py_memory_allocate_oom(num)) from OOM_TEST;
 count 
-------
     0
(1 row)

select count(py_memory_allocate_oom(aux)) from OOM_TEST;
ERROR:  plcontainer: Error receiving data from the client. Maybe retry later. (plcontainer.c:255)  (seg1 slice1 127.0.0.1:25433 pid=26450) (plcontainer.c:255)
select count(py_memory_allocate_oom(num)) from OOM_TEST;
 count 
-------
     0
(1 row)

select count(py_memory_allocate_normal(aux)) from OOM_TEST;
 count 
-------
     0
(1 row)

select count(py_memory_allocate_oom(aux)) from OOM_TEST;
ERROR:  plcontainer: Error receiving data from the client. Maybe retry later. (plcontainer.c:255)  (seg0 slice1 127.0.0.1:25432 pid=26449) (plcontainer.c:255)
select count(py_memory_allocate_normal(aux)) from OOM_TEST;
 count 
-------
     0
(1 row)

